apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kubeupdater.fullname-configmap" . }}
  namespace: kube-system
  labels:
    {{- include "kubeupdater.labels" . | nindent 4 }}
data:
  everything.repo: |
{{- if hasKey .Values "rawConfig" }}
{{ .Values.rawConfig | indent 4}}
{{- else }}
    [everything]
    name=everything
    enabled=1
    baseurl={{ .Values.base }}{{ .Values.version }}
    gpgkey = file:///etc/pki/rpm-gpg/{{ .Values.localGPGFileName }}
             {{ .Values.base }}{{ .Values.version }}/repodata/RPM-GPG-KEY
    gpgcheck = 1
    repo_gpgcheck = 1
    keepcache = 0
{{- end }}
