#!/bin/bash
CONTAINER="$1"
pushd $(dirname "$0")/"$CONTAINER"

[ ! -d hubbuildtools ] && git clone https://github.com/kfox1111/hubbuildtools

export AUTO_PREFIX=apk-version
export AUTO_PREFIX_PACKAGE=ipmitool
export NEW_BUILD=x
export IMAGE_NAME=pnnlmiscscripts/ipmitool:latest
export DOCKER_TAG=latest
export DOCKER_REPO=pnnlmiscscripts/ipmitool

hubbuildtools/hubhookhelpers/build
RES=$?

if [ $RES -eq 1 ]; then
	echo Nothing changed. Skipping.
	exit 0
fi
if [ $RES != 0 ]; then
	echo Something went wrong. Failing.
	exit $RES
fi

REVISION=$(hubbuildtools/fetchlocalrevision.sh "$IMAGE_NAME")

docker tag "$IMAGE_NAME" "$DOCKER_REPO:$REVISION"

docker images

echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

docker push "$DOCKER_REPO:$REVISION"
docker push "$IMAGE_NAME"

popd
