{
 "title": "Hardware",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "IPMI Problems",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"ipmi_.*_state\", type != \"Entity Presence\", name != \"TPM Presence\"} == 2",
     "legendFormat": "{{ instance }} {{ __name__ }}"
    },
    {
     "expr": "{__name__=~\"ipmi_.*_state\", __name__ != \"ipmi_chassis_power_state\"} == 1",
     "legendFormat": "{{ instance }}"
    },
    {
     "expr": "up{job=\"ipmi-exporter\"} < 1",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Collectors not collecting",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "ipmi_up != 1",
     "legendFormat": "{{ collector }}: {{ instance }}"
    }
   ]
  },
  {
   "title": "Memory ECC Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_edac_uncorrectable_errors_total[1m])",
     "legendFormat": "Uncorrectable: {{ instance }}"
    },
    {
     "expr": "rate(node_edac_correctable_errors_total[1m])",
     "legendFormat": "Correctable: {{ instance }}"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "fahrenheit" }
   ],
   "targets": [
    {
     "expr": "(ipmi_temperature_celsius * 9/5) + 32",
     "legendFormat": "{{ instance }} - {{ name }}"
    }
   ]
  },
  {
   "title": "Fan Speeds",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "RPM" }
   ],
   "targets": [
    {
     "expr": "avg without(pod)(ipmi_fan_speed_rpm) > 1500",
     "legendFormat": "{{ instance }} {{ name }}"
    },
    {
     "expr": "avg without(pod)(ipmi_fan_speed_rpm) <= 1500",
     "legendFormat": "SLOW {{ instance}} {{name}}"
    }
   ]
  },
  {
   "title": "Power in Watts",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "expr": "avg without(pod)(ipmi_dcmi_power_consumption_watts)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "SEL Log free space",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "avg without(pod) (ipmi_sel_free_space_bytes)",
     "legendFormat": "{{ instance }}"
    }
   ]
  }
 ]
}