apiVersion: v1
kind: Service
metadata:
  name: {{ include "pnnlmiscscripts.k8s-node-image-full.anaconda.fullname" . }}
  labels:
    {{- include "pnnlmiscscripts.k8s-node-image-full.labels" . | nindent 4 }}
    app.kubernetes.io/component: anaconda
    svc: anaconda
spec:
  type: {{ .Values.anaconda.service.type }}
  ports:
    - port: {{ .Values.anaconda.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "pnnlmiscscripts.k8s-node-image-full.selectorLabels" . | nindent 4 }}
    svc: anaconda
