{{- if .Values.ingress.enabled -}}
{{- $dot := . }}
{{- $prefix := include "pnnlmiscscripts.k8s-node-image-full.ingress.prefix" . }}
{{- $pxeprefix := printf "%s/images/pxeboot" $prefix }}
{{- $aFullName := include "pnnlmiscscripts.k8s-node-image-full.anaconda.fullname" . -}}
{{- $nFullName := include "pnnlmiscscripts.k8s-node-image-full.k8s-node.fullname" . -}}
{{- if and .Values.ingress.className (not (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion)) }}
  {{- if not (hasKey .Values.ingress.annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set .Values.ingress.annotations "kubernetes.io/ingress.class" .Values.ingress.className}}
  {{- end }}
{{- end }}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ include "pnnlmiscscripts.k8s-node-image-full.fullname" . }}
  labels:
    {{- include "pnnlmiscscripts.k8s-node-image-full.labels" . | nindent 4 }}
  annotations:
{{- if .Values.ingress.regex }}
    nginx.ingress.kubernetes.io/rewrite-target: /$1
{{- end }}
{{- if eq (len .Values.ingress.tls) 0 }}
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
{{- end }}
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if and .Values.ingress.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - http:
        paths:
          - path: {{ dict "dot" $dot "prefix" $prefix "suffix" "" "type" "d" | include "pnnlmiscscripts.k8s-node-image-full.ingress" }}
            {{- if semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion }}
            pathType: Prefix
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ $nFullName }}
                port:
                  name: http
              {{- else }}
              serviceName: {{ $nFullName }}
              servicePort: http
              {{- end }}
          - path: {{ dict "dot" $dot "prefix" $prefix "suffix" "vmlinuz" "type" "f" | include "pnnlmiscscripts.k8s-node-image-full.ingress" }}
            {{- if semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion }}
            pathType: Prefix
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ $aFullName }}
                port:
                  name: http
              {{- else }}
              serviceName: {{ $aFullName }}
              servicePort: http
              {{- end }}
          - path: {{ dict "dot" $dot "prefix" $prefix "suffix" "initrd.img" "type" "f" | include "pnnlmiscscripts.k8s-node-image-full.ingress" }}
            {{- if semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion }}
            pathType: Prefix
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ $aFullName }}
                port:
                  name: http
              {{- else }}
              serviceName: {{ $aFullName }}
              servicePort: http
              {{- end }}
          - path: {{ dict "dot" $dot "prefix" $pxeprefix "suffix" "vmlinuz" "type" "f" | include "pnnlmiscscripts.k8s-node-image-full.ingress" }}
            {{- if semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion }}
            pathType: Prefix
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ $aFullName }}
                port:
                  name: http
              {{- else }}
              serviceName: {{ $aFullName }}
              servicePort: http
              {{- end }}
          - path: {{ dict "dot" $dot "prefix" $pxeprefix "suffix" "initrd.img" "type" "f" | include "pnnlmiscscripts.k8s-node-image-full.ingress" }}
            {{- if semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion }}
            pathType: Prefix
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ $aFullName }}
                port:
                  name: http
              {{- else }}
              serviceName: {{ $aFullName }}
              servicePort: http
              {{- end }}
          - path: {{ dict "dot" $dot "prefix" $prefix "suffix" "LiveOS" "type" "d" | include "pnnlmiscscripts.k8s-node-image-full.ingress" }}
            {{- if semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion }}
            pathType: Prefix
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ $aFullName }}
                port:
                  name: http
              {{- else }}
              serviceName: {{ $aFullName }}
              servicePort: http
              {{- end }}
          - path: {{ dict "dot" $dot "prefix" $prefix "suffix" ".treeinfo" "type" "f" | include "pnnlmiscscripts.k8s-node-image-full.ingress" }}
            {{- if semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion }}
            pathType: Prefix
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ $aFullName }}
                port:
                  name: http
              {{- else }}
              serviceName: {{ $aFullName }}
              servicePort: http
              {{- end }}
      {{- if . }}
      host: {{ . | quote }}
      {{- end }}
    {{- end }}
{{- end }}
