apiVersion: v1
kind: Service
metadata:
  name: {{ include "pnnlmiscscripts.k8s-node-image-full.k8s-node.fullname" . }}
  labels:
    {{- include "pnnlmiscscripts.k8s-node-image-full.labels" . | nindent 4 }}
    app.kubernetes.io/component: k8s-node
    svc: k8s-node
spec:
  type: {{ .Values.k8sNode.service.type }}
  ports:
    - port: {{ .Values.k8sNode.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "pnnlmiscscripts.k8s-node-image-full.selectorLabels" . | nindent 4 }}
    svc: k8s-node
