## Default values for magic-namespace

# Uncomment and set to override the namespace that will be created.
# namespace: default

# Extra namespace attributes
# namespaceAttributes:
  # Labels to be added to the namespace definition
  # labels: {}

  # Annotations to be added to the namespace definition
  # annotations: {}

## Optional additional ServiceAccounts
serviceAccounts: []
# - some-service-account
# - another-service-account

## Optional additional RoleBindings. It is a good idea to specify at least one
## to grant administrative permissions to a user or group.
# roleBindings:
# - name: admin-group-admin
#   role:
#     ## Valid values are "Role" or "ClusterRole"
#     kind: ClusterRole
#     name: admin
#   subject:
#     ## Valid values are "User", "Group", or "ServiceAccount"
#     kind: Group
#     name: <group>
