#!/bin/bash -e

RAWCONTAINER="$1"
SUBBUILD="$2"
if [ "x$SUBBUILD" == "x" -o "x$SUBBUILD" == "xlatest" ]; then
	CONTAINER="$RAWCONTAINER"
	SUBBUILD=latest
else
	CONTAINER="$RAWCONTAINER-$(echo $SUBBUILD | tr '.' '-')"
fi

if [ "x$REVISION" == "x" ]; then
	echo REVISION is not set.
	exit -1
fi

mkdir -p $(dirname "$0")/"$CONTAINER"

pushd $(dirname "$0")/"$CONTAINER"


export DOCKER_TAG="$SUBBUILD"
export CPREFIX="pnnlmiscscripts"

[ -f buildenv ] && . ../../../containers/"$RAWCONTAINER"/buildenv

if [ "x$IMAGE_NAME" == "x" ]; then
	export IMAGE_NAME="${DOCKER_REPO}:${DOCKER_TAG}"
fi

SUBREPO="$RAWCONTAINER"
if [ "x$DOCKER_REPO" != "x" ]; then
	SUBREPO=$(echo "$DOCKER_REPO" | sed "s@$CPREFIX/@@g")
fi

cat > Chart.yaml <<EOF
apiVersion: v1
appVersion: "$REVISION"
description: A Helm chart for Kubernetes
name: $CONTAINER
version: 2.0.0
EOF

mkdir -p templates
cat > templates/_helpers.tpl <<EOF
{{- define "$CPREFIX.$CONTAINER.server" -}}
{{- if and (hasKey . "section") (hasKey .section "server") .section.server -}}
{{ .section.server }}
{{- else -}}
docker.io
{{- end -}}
{{- end -}}

{{- define "$CPREFIX.$CONTAINER.prefix" -}}
{{- if and (hasKey . "section") (hasKey .section "prefix") .section.prefix -}}
/{{ .section.prefix }}
{{- end -}}
{{- end -}}

{{- define "$CPREFIX.$CONTAINER.org" -}}
{{- if and (hasKey . "section") (hasKey .section "org") .section.org -}}
{{ .section.org }}
{{- else -}}
$CPREFIX
{{- end -}}
{{- end -}}

{{- define "$CPREFIX.$CONTAINER.repo" -}}
{{- if and (hasKey . "section") (hasKey .section "repo") .section.repo -}}
{{ .section.repo }}
{{- else -}}
$SUBREPO
{{- end -}}
{{- end -}}

{{- define "$CPREFIX.$CONTAINER.tag" -}}
{{- if and (hasKey . "section") (hasKey .section "tag") .section.tag -}}
{{ .section.tag }}
{{- else -}}
$REVISION
{{- end -}}
{{- end -}}

{{- /*
How to use:
  {{ dict "dot" . "section" (index .Values "$CONTAINER") | include "$CPREFIX.$CONTAINER.image" }}
*/ -}}
{{- define "$CPREFIX.$CONTAINER.image" -}}
{{- include "$CPREFIX.$CONTAINER.server" . -}}{{- include "$CPREFIX.$CONTAINER.prefix" . -}}/{{- include "$CPREFIX.$CONTAINER.org" . -}}/{{- include "$CPREFIX.$CONTAINER.repo" . -}}:{{- include "$CPREFIX.$CONTAINER.tag" . -}}
{{- end -}}
EOF

mkdir -p files
cat > files/metadata.json <<EOF
{
  "server": "docker.io",
  "prefix": "",
  "org": "$CPREFIX",
  "repo": "$SUBREPO",
  "tag": "$REVISION"
}
EOF

pushd ../image-library-charts/docs
helm template "../../$CONTAINER" > /dev/null
helm package "../../$CONTAINER"
popd
