#!/bin/bash

set -e

#fetch helm in a way build can use...

pushd $(dirname "$0")
[ ! -d image-library-charts ] && git clone https://github.com/pnnl-miscscripts/image-library-charts
[ ! -d hubbuildtools ] && git clone https://github.com/kfox1111/hubbuildtools

if [ "x$TRAVIS" != "x" -o "x$GITHUB_ACTION" != "x" ]; then
	curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 > get_helm.sh
	chmod 700 get_helm.sh
	./get_helm.sh
	helm repo add stable https://charts.helm.sh/stable
fi

cd image-library-charts

mkdir -p tags

CHANGE=0
for CONTAINER in ipmitool ipmi-exporter dhcpd inotify-tools chronyd debug-toolbox anaconda-nginx anaconda-nginx9 k8s-node-image-nginx k8s-node-image-nginx9 pixiecore smartctl-exporter; do
	case "$CONTAINER" in
	k8s-node-image-nginx)
		SUBBUILDS="1.21 1.22 1.23 1.24"
		;;
	k8s-node-image-nginx9)
		SUBBUILDS="1.24 1.25 1.28"
		;;
	*)
		SUBBUILDS="latest"
		;;
	esac
	for SUBBUILD in $SUBBUILDS; do
		unset DOCKER_REPO
		export DOCKER_REPO=$(
			[ -f ../../../containers/"$CONTAINER"/buildenv ] && . ../../../containers/"$CONTAINER"/buildenv
			[ "x$DOCKER_REPO" != "x" ] && echo "$DOCKER_REPO" || \
			echo "pnnlmiscscripts/$CONTAINER"
		)
		unset DOCKER_TAG
		export DOCKER_TAG=$(
			[ -f ../../../containers/"$CONTAINER"/buildenv ] && . ../../../containers/"$CONTAINER"/buildenv
			[ "x$DOCKER_TAG" != "x" ] && echo "$DOCKER_TAG" || \
			echo "$SUBBUILD"
		)
		export REVISION=$(../hubbuildtools/hubcurlrevision.sh "$DOCKER_REPO" "$DOCKER_TAG")
		echo Revision: $REVISION
		if [ "$REVISION" == "null" ]; then
			echo BAD REVISION
			exit 1
		fi
		FOUND=0
		if [ -f "tags/$CONTAINER-$SUBBUILD" ]; then
			if [ "x2 $REVISION" == "x$(cat tags/$CONTAINER-$SUBBUILD)" ]; then
				FOUND=1
				echo $CONTAINER $SUBBUILD already built.
			fi
		fi
		if [ $FOUND -eq 0 ]; then
			CHANGE=1
			echo $CONTAINER building...
			../build "$CONTAINER" "$SUBBUILD"
			echo "2 $REVISION" > "tags/$CONTAINER-$SUBBUILD"
		fi
	done
done
if [ $CHANGE -eq 1 ]; then
	pushd docs
	helm repo index .
	popd
	git add --all :/ && git commit -m "Update repo"
	git push https://pnnlmiscscriptsci:"$GITHUB_LIBRARY_CHARTS_TOKEN"@github.com/pnnl-miscscripts/image-library-charts
fi
