{{- if .Values.ingressClass.enabled }}
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: {{ .Values.ingressClass.name }}
  labels:
    {{- include "tenant-namespace-operator.labels" . | nindent 4 }}
spec:
  controller: k8s.io/ingress-nginx
{{- end }}
