---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "tenant-namespace-operator.fullname" . }}-le
  labels:
{{ include "tenant-namespace-operator.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "tenant-namespace-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "tenant-namespace-operator.fullname" . }}-le
  apiGroup: rbac.authorization.k8s.io
