apiVersion: rbac.authorization.k8s.io/v1
{{- if eq .Values.mode "cluster" }}
kind: ClusterRole
{{- else if eq .Values.mode "cluster" }}
kind: Role
{{- end }}
metadata:
  name: {{ include "tenant-namespace-operator.fullname" . }}
  labels:
{{ include "tenant-namespace-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - services/finalizers
  - endpoints
  - events
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  - replicasets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  - prometheusrules
  verbs:
  - get
  - create
  - list
  - delete
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resourceNames:
  - tenant-namespace-operator
  resources:
  - deployments/finalizers
  verbs:
  - update
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
- apiGroups:
  - apps
  resources:
  - replicasets
  - deployments
  verbs:
  - get
- apiGroups:
  - miscscripts.pnnl.gov
  resources:
  - '*'
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
