apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pnnlmiscscripts.k8s-node-image-full.anaconda.fullname" . }}
  labels:
    {{- include "pnnlmiscscripts.k8s-node-image-full.labels" . | nindent 4 }}
    app.kubernetes.io/component: anaconda
    svc: anaconda
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "pnnlmiscscripts.k8s-node-image-full.selectorLabels" . | nindent 6 }}
      svc: anaconda
  template:
    metadata:
      {{- with .Values.anaconda.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "pnnlmiscscripts.k8s-node-image-full.selectorLabels" . | nindent 8 }}
        svc: anaconda
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: main
          command: ["nginx", "-g", "daemon off;"]
          image: {{ dict "dot" . "section" (index .Values "anaconda").image | include "pnnlmiscscripts.anaconda-nginx9.image" }}
          imagePullPolicy: {{ .Values.anaconda.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          lifecycle:
            preStop:
              exec:
                command:
                - /bin/sh
                - -c
                - nginx -s quit
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
