{{- if .Values.letsencrypt.enabled }}
{{- $name := .Values.magicnamespace.namespace }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: default-tls
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "namespace.labels" . | nindent 4 }}
spec:
  secretName: default-tls
  dnsNames:
  - {{ $name }}.{{ .Values.subdomain }}
  - "*.{{ $name }}.{{ .Values.subdomain }}"
  issuerRef:
    name: letsencrypt-production
    kind: Issuer
{{- end }}
