{{- if .Values.gitlabRunner.enabled }}
apiVersion: miscscripts.pnnl.gov/v1beta1
kind: GitlabRunner
metadata:
  name: {{ .Values.gitlabRunner.name }}
  namespace: {{ .Values.magicnamespace.namespace }}
  labels:
    {{- include "namespace.labels" . | nindent 4 }}
spec:
{{ toYaml .Values.gitlabRunner.spec | indent 2 }}
{{- end }}
