{{ if .Values.ingress.nginx.clusterRole }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pmstn-{{ .Values.magicnamespace.namespace }}-ic
  labels:
    {{- include "namespace.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.ingress.nginx.clusterRole }}
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}-ingress
  namespace: {{ .Release.Namespace | quote }}
{{ end }}
