{{- if .Values.limitRange.enabled }}
apiVersion: v1
kind: LimitRange
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.magicnamespace.namespace }}
  labels:
    {{- include "namespace.labels" . | nindent 4 }}
spec:
  limits:
{{ toYaml .Values.limitRange.limits | indent 4 }}
{{- end }}
