{{- if .Values.operatorGroup.enabled }}
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: {{ .Values.magicnamespace.namespace }}
  namespace: {{ .Values.magicnamespace.namespace }}
  labels:
    {{- include "namespace.labels" . | nindent 4 }}
spec:
  targetNamespaces:
  - {{ .Values.magicnamespace.namespace }}
{{- end }}
