#!/bin/bash

set -e

pushd $(dirname "$0")

[ ! -d charts ] && git clone https://github.com/pnnl-miscscripts/charts
[ ! -d hubbuildtools ] && git clone https://github.com/kfox1111/hubbuildtools

if [ "x$TRAVIS" != "x" ]; then
	curl https://raw.githubusercontent.com/helm/helm/master/scripts/get > get_helm.sh
	chmod 700 get_helm.sh
	./get_helm.sh
fi

mkdir -p charts/docs
mkdir -p charts/tags
mkdir -p charts/vers

helm repo add pnnl-miscscripts-image-library-charts https://pnnl-miscscripts.github.io/image-library-charts/
helm repo update

CHANGE=0
for CHART in console; do
	pushd "$CHART"
	helm dep up --skip-refresh
	FINGERPRINT=$((echo main
	cat Chart.yaml | sort | awk '{if(/^(appVersion|version|name):/){print $2}}' | sed 'N;N; s/\([^\n]*\)\n\([^\n]*\)\n\([^n]*\)/\2 \3 \1/g'
	echo deps
	ls charts | sort | while read line; do
		helm inspect chart charts/$line | sort | awk '{if(/^(appVersion|version|name):/){print $2}}' | sed 'N;N; s/\([^\n]*\)\n\([^\n]*\)\n\([^n]*\)/\2 \3 \1/g'
	done) | bzip2 -c | base64 | tr '\n' '=' | sed 's/=//g')
        VERSION=$(cat Chart.yaml | awk '{if(/^version:/){print $2}}')
	popd
	echo Version: $VERSION
	echo Fingerprint: $FINGERPRINT
	pushd charts
	FOUND=0
	if [ -f "tags/$CHART-latest" ]; then
		if [ "x$FINGERPRINT" == "x$(cat tags/$CHART-latest)" ]; then
			FOUND=1
			echo $CHART already built.
		fi
	fi
	if [ $FOUND -eq 0 ]; then
		CHANGE=1
		echo $CHART building...
		pushd docs/
		NEWVERSION="$VERSION"
		if [ -f ../vers/$CHART-latest ]; then
			echo Existing package found. Updating version.
			OLDVERSION=$(cat ../vers/$CHART-latest)
			MAJORVERSION=$(echo $OLDVERSION | awk -F . '{print $1}')
			MINORVERSION=$(echo $OLDVERSION | awk -F . '{print $2}')
			PATCHVERSION=$(echo $OLDVERSION | awk -F . '{print $3}')
			NEWPATCHVERSION=$((PATCHVERSION + 1))
			NEWVERSION="$MAJORVERSION.$MINORVERSION.$NEWPATCHVERSION"
			echo Old version: $OLDVERSION
			echo New version: $NEWVERSION
			sed -i "s/^version: .*/version: $NEWVERSION/" ../../$CHART/Chart.yaml
			sed -i "s/^appVersion: .*/appVersion: $NEWVERSION/" ../../$CHART/Chart.yaml
		fi
		helm package ../../$CHART
		popd
		echo "$FINGERPRINT" > "tags/$CHART-latest"
		echo "$NEWVERSION" > "vers/$CHART-latest"
	fi
	popd
done

pushd charts
if [ $CHANGE -eq 1 ]; then
	pushd docs
	helm repo index .
	popd
	git add --all :/ && git commit -m "Update repo"
	git push https://pnnlmiscscriptsci:"$GITHUB_LIBRARY_CHARTS_TOKEN"@github.com/pnnl-miscscripts/charts
fi
popd

popd
